// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ithobjnvgkztrvahfodk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0aG9iam52Z2t6dHJ2YWhmb2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzAwMjQsImV4cCI6MjA2ODI0NjAyNH0.H0ALnTKadPc6iI7HJm5spGOrJnrwaR2hn_QOetYkyM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});