// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbuycfubxsuxvdstjhel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidXljZnVieHN1eHZkc3RqaGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Nzc0OTQsImV4cCI6MjA2ODI1MzQ5NH0.-ldztUJj1BKV60lUmfrkPNdU_DM02PjVj243mOV_5e4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});